---
- hosts: all
  become: yes
  vars_files:
    - playbook/group_vars/main.yml 
  roles:
    # TODO-ansible: create a user sysadmin or the like to be the default super user for our tasks
    - vim
    - baseapps
    - diaspora

  tasks:
    - name: Say hi
      ping:

