#This is added at rsyslog.d 
$template DynamicFolder, "/var/log/sl/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%" #this should be at host, but now is here for testing locally

local0.=notice   ?DynamicFolder
#local0.=notice		@@trantor 
