# This script must be located in the client machines, at /etc/rsyslog.d/

*.* @192.168.X.X #for forwarding by udp 
*.* @@192.168.X.X #for forwarding by tcp
*.* :omrelp:192.168.X.X:YYYY #for forwarding by RELP. YYYY is a port that must be specified, due to RELP do not have a standard port
