# This script modifies the host  rsyslog to receive the logs from other machines
#

module(load="imtcp")
input(type="imtcp" port="514")


#a template to organize the host.

$template DynamicFolder, "/var/log/sl/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%.log"
    
local0.=notice 		?DynamicFolder
