# This script modifies the Trantor rsyslog to receive the logs from other machines

module(load="imudp")
input(type="imudp" port="514") #enables udp communication by port 514

module(load="imtcp")
input(type="imtcp" port="514") #enables tcp communication by port 514


#TODO: 
#firewall-cmd --permanent --add-port=514/udp
#firewall-cmd --permanent --add-port=515/tcp
#firewall-cmd --reload
#
#semanage port -a -t syslogd_port_t -p udp 514
#semanage port -a -t syslogd_port_t -p tcp 514 



#a template to organize the host.

$template DynamicFolder, "/var/log/sl/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%.log"
    
local0.=notice 		?DynamicFolder
