---
# TODO: Use git ansible module and check for releases/tags
# TODO: everything in here will be refactored
# DOCS: https://stackoverflow.com/questions/33672491/how-to-use-ansible-to-provision-vim-vundle-plugin

- name: Install dependencies
  package:
    name: ["vim", "git"] # TODO: separate this list to an external yml
    state: present

- name: Get vimrc
  get_url: # Abstract user name into a variable
    url: https://raw.githubusercontent.com/OscHer/dotfiles/main/vim/vimrc 
    dest: /home/vagrant/.vimrc
    backup: true # just in case
    group: vagrant
    mode: 0664
    owner: vagrant

# TODO: every spelling task will be refactored into a separate yaml
- name: create wordlist directory
  file:
    path: /home/vagrant/.vim/spell
    state: directory
    owner: vagrant
    group: vagrant

# TODO: refactor username into a variable
- name: Deploy wordlists from github
  get_url:
    url: https://github.com/OscHer/dotfiles/blob/main/vim/vim/spell/{{ item }}?raw=true
    dest: /home/vagrant/.vim/spell/
    backup: false
    owner: vagrant
    group: vagrant
    mode: 0664
  loop: # TODO: git-clone-form this to increase elegance
    - devel.utf-8.spl
    - es.utf-8.spl

# TODO: Separate vundle related tasks to an included file
- name: git clone vundle repos
  ansible.builtin.git:
    # TODO: check bare parameter of this module
    # TODO: change ownership of this file tree
    clone: true
    dest: /home/vagrant/.vim/bundle/Vundle.vim
    repo: https://github.com/VundleVim/Vundle.vim.git
    version: master
  become: yes
  become_user: vagrant

# TODO: refactor user and user home dir
- name: install plugins
  ansible.builtin.shell: >
    echo -ne '\n' | vim -E -s -c "source /home/vagrant/.vimrc" -c PluginInstall -c qa
  register: resultvim
  become_user: vagrant
  become: true
  failed_when: ( resultvim.rc not in [0,1] )

# TODO: output result of installation
- name: debug install vim
  debug:
    msg: "{{ resultvim }}"
# TODO: deploy abbreviations.vim
